In [38]:
import IPython.display as ipd
% pylab inline
import os
import librosa
import librosa.display
import pandas as pd
import glob 
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split 

Populating the interactive namespace from numpy and matplotlib


In [63]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))



plt.figure(figsize=(12, 4))
librosa.display.waveplot(data, sr=sampling_rate)

data1, sampling_rate = librosa.load('/Users/shikhagupta/Desktop/animal/nftsounds/Elephant/elephan6 (1).mp3')

plt.figure(figsize=(12, 4))
librosa.display.waveplot(data1, sr=sampling_rate)

In [14]:
elephant=[]

path = '/Users/shikhagupta/Desktop/animal/nftsounds/Elephant/'


In [19]:
def extract_features(file_name):
   
    try:
        audio, sample_rate = librosa.load(file_name, res_type='kaiser_fast') 
        mfccs = librosa.feature.mfcc(y=audio, sr=sample_rate, n_mfcc=40)
        mfccsscaled = np.mean(mfccs.T,axis=0)
        
        
    except Exception as e:
        print("Error encountered while parsing file: ", file)
        return None 
     
    return mfccsscaled
    

In [43]:

features = []
path = '/Users/shikhagupta/Desktop/animal/nftsounds/Elephant/'
for filename in glob.glob(os.path.join(path, '*.mp3')):
    # do your stuff
   
    #d,sampling_rate = librosa.load(filename)
    #mfccs = np.mean(librosa.feature.mfcc(y=d, sr=sample_rate, n_mfcc=40).T,axis=0)
    #elephant.append(d)
    data = extract_features(filename)
    features.append([data, "elephant"])
    
path = '/Users/shikhagupta/Desktop/animal/nftsounds/Dog/'
for filename in glob.glob(os.path.join(path, '*.mp3')):
    # do your stuff
   
    #d,sampling_rate = librosa.load(filename)
    #mfccs = np.mean(librosa.feature.mfcc(y=d, sr=sample_rate, n_mfcc=40).T,axis=0)
    #elephant.append(d)
    data = extract_features(filename)
    features.append([data, "dog"])

path = '/Users/shikhagupta/Desktop/animal/nftsounds/Bat/'
for filename in glob.glob(os.path.join(path, '*.mp3')):
    # do your stuff
   
    #d,sampling_rate = librosa.load(filename)
    #mfccs = np.mean(librosa.feature.mfcc(y=d, sr=sample_rate, n_mfcc=40).T,axis=0)
    #elephant.append(d)
    data = extract_features(filename)
    features.append([data, "bat"])

path = '/Users/shikhagupta/Desktop/animal/nftsounds/Pig/'
for filename in glob.glob(os.path.join(path, '*.mp3')):
    # do your stuff
   
    #d,sampling_rate = librosa.load(filename)
    #mfccs = np.mean(librosa.feature.mfcc(y=d, sr=sample_rate, n_mfcc=40).T,axis=0)
    #elephant.append(d)
    data = extract_features(filename)
    features.append([data, "pig"])

    

featuresdf = pd.DataFrame(features, columns=['feature','class_label'])
 


In [45]:
from keras.utils import to_categorical

X = np.array(featuresdf.feature.tolist())
y = np.array(featuresdf.class_label.tolist())
le = LabelEncoder()
yy = to_categorical(le.fit_transform(y)) 
x_train, x_test, y_train, y_test = train_test_split(X, yy, test_size=0.2, random_state = 42)

In [62]:
z=[0]*16
v=[[0.5]*16]*40
w=[[0.5]*4]*16
o=[0]*4

for i in range(len(x_train)):
    for j in range(16):
        for k in range(40):
            z[j]=z[j]+v[k][j]*x_train[i][k]
        z[j]=sigmoid[z[j]]
        
    for p in range(4):
        for q in range(16):
            o[p]=o[p]+w[q][p]*z[q]
        o[p]=sigmoid[o[p]]
            

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
0
1
2
3
4


In [54]:
print (X)

[[-1.24706142e+02  1.95196561e+02 -5.37254209e+01 ... -3.83482184e-01
   2.17578016e+00 -2.77288423e+00]
 [-1.99284908e+02  1.76525333e+02 -9.16158115e+01 ...  4.24313253e+00
  -1.02921023e+00  2.24986619e+00]
 [-1.20491181e+02  1.37434002e+02 -1.32393635e+02 ... -6.10496517e-01
   1.24227723e+00 -5.70140348e+00]
 ...
 [-1.67809597e+02  1.99122603e+02 -7.34455487e+01 ...  4.94372108e+00
  -6.56605484e-01 -3.34243084e+00]
 [-4.31848346e+02  1.40397997e+02 -2.31268656e+01 ... -2.80765509e+00
  -6.10484220e-01 -2.72993071e+00]
 [-1.33017394e+02  1.46150176e+02 -1.38312666e+02 ... -2.18446067e+00
   6.89742594e+00 -2.96812616e+00]]


In [51]:
print(len(X[0]))
print(y)
print(yy)

40
['elephant' 'elephant' 'elephant' 'elephant' 'elephant' 'elephant'
 'elephant' 'elephant' 'elephant' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog'
 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog' 'dog'
 'bat' 'bat' 'bat' 'bat' 'bat' 'bat' 'bat' 'bat' 'bat' 'bat' 'bat' 'bat'
 'pig' 'pig' 'pig' 'pig' 'pig' 'pig' 'pig' 'pig' 'pig' 'pig']
[[0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0.

In [29]:
print(features[0])

[array([-1.24706142e+02,  1.95196561e+02, -5.37254209e+01,  2.60796185e+01,
       -1.63663467e+01, -1.95042175e+00,  1.41099332e+01, -2.41663771e+01,
        3.10314681e+00, -4.12396424e+00, -1.85142321e+00, -5.26414203e-01,
       -1.37681457e+01, -2.35213972e+00, -1.52347009e+01, -6.47307042e+00,
       -1.25774135e+00, -1.38325180e+01, -1.96003293e+00, -3.24969117e+00,
        9.78066817e-01,  2.80908538e+00, -3.66741827e-01,  6.58655125e+00,
       -2.22039843e+00,  1.63320938e-01,  2.18259725e+00, -1.29161682e+00,
        3.56562600e+00, -2.33171031e+00,  1.79413113e+00,  3.29886584e+00,
        2.06514217e-01,  4.14523645e+00, -2.69200512e+00, -1.04327123e+00,
        8.05093044e-01, -3.83482184e-01,  2.17578016e+00, -2.77288423e+00]), 'elephant']


In [37]:
#print(len(features))
print(featuresdf.class_label)

0    elephant
1    elephant
2    elephant
3    elephant
4    elephant
5    elephant
6    elephant
7    elephant
8    elephant
Name: class_label, dtype: object


In [44]:
print(featuresdf)

                                              feature class_label
0   [-124.70614199041682, 195.19656124326548, -53....    elephant
1   [-199.28490824759217, 176.52533269502436, -91....    elephant
2   [-120.49118136825949, 137.434002118908, -132.3...    elephant
3   [-183.08887123070693, 181.3369378013885, -89.4...    elephant
4   [-246.02034246424958, 122.96516476695308, -65....    elephant
5   [-85.09307774558673, 121.22709911330324, -54.7...    elephant
6   [-189.0855275564496, 164.60785857967002, -90.3...    elephant
7   [-147.55477250118886, 217.9647587092899, -37.1...    elephant
8   [-147.55477250118886, 217.9647587092899, -37.1...    elephant
9   [-137.79003562548746, 202.91674051185913, -72....         dog
10  [-130.56725893859655, 160.32640876273155, -48....         dog
11  [-251.69142707137271, 77.30019366572164, -35.2...         dog
12  [-185.65773229005663, 166.3340759066157, -103....         dog
13  [-234.51270352591254, 211.8217047487161, -12.4...         dog
14  [-229.

In [78]:
for x in featuresdf:
    print("output")
    print(x) 
    #plt.figure(figsize=(12, 4))
    #librosa.display.waveplot(x)
    

output
feature
output
class_label


In [38]:
print(sampling_rate)

22050


In [49]:
import struct
class WavFileHelper():
    def read_file_properties(self, filename):
        wave_file = open(filename,"rb")
        riff = wave_file.read(12)
        fmt = wave_file.read(36)
        num_channels_string = fmt[10:12]
        num_channels = struct.unpack('<H', num_channels_string)[0]
        sample_rate_string = fmt[12:16]
        sample_rate = struct.unpack("<I",sample_rate_string)[0]
        bit_depth_string = fmt[22:24]
        bit_depth = struct.unpack("<H",bit_depth_string)[0]
        return (num_channels, sample_rate, bit_depth)